<h1><?php echo __('Customer reviews'); ?></h1>
<?php $orderReviewsCollection = $block->getOrderReviews(); ?>
<?php if($orderReviewsCollection->getSize() > 0): ?>
<div class="review-text">
    <p><?php echo __('A better service is possible because our clients give us his opinion. Check his opinions to know what are thinking our clients for about us:'); ?></p>
</div>
<?php foreach($orderReviewsCollection as $orderReview): ?>
    <div class="review">
        <div>
            <div class="left">
                <?php echo __('Delivery:'); ?>
            </div><!--
            --><div class="right">
                <?php for ($i=1; $i <= 5; $i++): ?>
                    <span class="fa fa-star <?php echo $orderReview->getShipping() >= $i ? 'checked' : '' ?>"></span>
                <?php endfor; ?>
            </div>
        </div>
        <div>
            <div class="left">
                <?php echo __('Product:'); ?>
            </div><!--
            --><div class="right">
                <?php for ($i=1; $i <= 5; $i++): ?>
                    <span class="fa fa-star <?php echo $orderReview->getProduct() >= $i ? 'checked' : '' ?>"></span>
                <?php endfor; ?>
            </div>
        </div>
        <div>
            <div class="left">
                <?php echo __('Customer support:'); ?>
            </div><!--
            --><div class="right">
                <?php for ($i=1; $i <= 5; $i++): ?>
                    <span class="fa fa-star <?php echo $orderReview->getCustomerSupport() >= $i ? 'checked' : '' ?>"></span>
                <?php endfor; ?>
            </div>
        </div>
        <?php if ($orderReview->getComment()): ?>
            <div>
                <div class="left">
                    <?php echo __('Comment:'); ?>
                </div><!--
                --><div class="right">
                     <?php echo $orderReview->getComment(); ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
<?php endforeach; ?>
<?php else: ?>
<div class="review-text">
    <p><?php echo __('Sorry, we can\'t show any review.'); ?></p>
</div>
<?php endif; ?>